name: Push Docker Image

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Substitute variables
      uses: actions/checkout@v2

      uses: microsoft/variable-substitution@v1 
      with:
        files: 'src/Genesis.Case/Api/appsettings.json'
      env:
        Email.Login: ${{ secrets.EMAIL_ADDRESS }}
        Email.Password: ${{ secrets.EMAIL_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build Docker Image
      run: |
        docker build . --tag ghcr.io/Bardin08/genesis-case-task:latest
        docker run ghcr.io/Bardin08/genesis-case-task:latest
        docker push ghcr.io/Bardin08/genesis-case-task:latest
